version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: diego-spiderfoot_server_1
      APP_PORT: 8080

  server:
    image: dtagdevsec/spiderfoot:24.04.1
    user: "0:0"
    init: true
    restart: on-failure
    environment:
      - HOME=/home/spiderfoot
    volumes:
      - ${APP_DATA_DIR}/data:/home/spiderfoot/.spiderfoot
